import { FileData } from "@/types/type";

export const TEST_FILES: FileData[] = [
  {
    id: 1,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 2,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 3,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 4,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 5,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 6,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 7,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 8,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
  {
    id: 9,
    fileName: "test.png",
    uploadDate: "2025/12/1",
    tokenCount: "1,234tokens",
    fileSize: "1.2MB",
    url: "/document.png",
  },
];
